// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: Dflutter pub cache cleanefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbKwQvctDdH2FUzfQCib5rLlo81AQ3UpI',
    appId: '1:111241786437:android:b3ad541b93e20406841f2c',
    messagingSenderId: '111241786437',
    projectId: 'mobilkalaba',
    databaseURL: 'https://mobilkalaba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilkalaba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tXudPh9hKatB-NiSHUcTpI7xGeFqvmA',
    appId: '1:111241786437:ios:1cf097ad72ea3b5e841f2c',
    messagingSenderId: '111241786437',
    projectId: 'mobilkalaba',
    databaseURL: 'https://mobilkalaba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobilkalaba.appspot.com',
    iosBundleId: 'com.example.lab2',
  );
}
